# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1496361d08da15df81edcbd13008f240a2ca546a200feac4dabdaa3e5a1a1d57ad40a9e3197a505161ce1935a5b06e7ef5039456eff4f7196b8d6509cf493e62

test:
  secret_key_base: c6c754d03e86b3ef3fb7d3a291bd6ab2dad198105979344ebd33ddb346de687cf75e00df4fa33a68159617d7c751f9b258181e25aa41c50cccea5df98ed92485

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
